version: '3'


services:
  db:
    container_name: 'watchlist-db'
    image: 'postgres:12'
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: arif
      POSTGRES_DB: watchlist
  db-test:
    container_name: 'watchlist-db-test'
    image: 'postgres:12'
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: arif
      POSTGRES_DB: watchlist-test


volumes:
  pgdata: {}